- name: Create source address on fortigate
  hosts: fortigates
  collections:
   - fortinet.fortios
  connection: httpapi


  vars:
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80

  tasks:
  - name: Mgmt network
    fortinet.fortios.fortios_firewall_address:
      vdom: "root"
      state: "present"
      firewall_address:
        name: "Mgmt-network"
        subnet: "192.168.85.0 255.255.255.0"
