- hosts: fortigates
  collections:
   - fortinet.fortios
  connection: httpapi
  

  vars:
   ansible_httpapi_use_ssl: no
   ansible_httpapi_validate_certs: no
   ansible_httpapi_port: 80

  tasks:
  - name: Rename firewall via API
    fortinet.fortios.fortios_system_global:
      vdom: "root"
      system_global:
        admintimeout: "60"
        hostname: "Fortigate1"
